name: Android CI

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    if: ${{ true }} # at the moment this simply wastes our minutes, we will enable it when we have unit tests etc.

    runs-on: ubuntu-latest

    env:
      RVX_SENTRY_DSN: ${{ vars.RVX_SENTRY_DSN }}
      RVX_ANALYSIS_ENABLED: ${{ vars.RVX_ANALYSIS_ENABLED }}
      RVX_ANALYSIS_BASEURL: ${{ vars.RVX_ANALYSIS_BASEURL }}
      RVX_DEBUG_APP_NAME: "Revolt"
      RVX_BUILD_FLAVOUR_ID: ${{ vars.RVX_BUILD_FLAVOUR_ID }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: gradle


      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew --no-daemon assembleRelease

      - name: Get wget
        run: sudo apt-get install wget

      - name: Dowload signer
        run: wget https://github.com/appium-boneyard/sign/releases/download/1.0/sign-1.0.jar

      - name: Sign APK with testkeys
        run: java -jar sign-1.0.jar app/build/outputs/apk/release/app-release-unsigned.apk --override

      - name: Archive release APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          retention-days: 5
          path: |
            app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Upload Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
         file: "app/build/outputs/apk/release/app-release-unsigned.apk"
         tags: true
         draft: true
